export const StateNames = {
    MG: "Minas Gerais",
    SE: "Sergipe",
    PE: "Pernambuco",
    MA: "Maranhão",
    RN: "Rio Grande do Norte",
    RO: "Rondônia",
    TO: "Tocantins",
    BA: "Bahia",
    SP: "São Paulo",
    AL: "Alagoas",
    DF: "Distrito Federal",
    PA: "Pará",
    PI: "Piauí",
    SC: "Santa Catarina",
    MT: "Mato Grosso",
    AP: "Amapá",
    AM: "Amazonas",
    GO: "Goiás",
    PR: "Paraná",
    ES: "Espírito Santo",
    RS: "Rio Grande do Sul",
    CE: "Ceará",
    MS: "Mato Grosso do Sul",
    PB: "Paraíba",
    RR: "Roraima",
    AC: "Acre",
    RJ: "Rio de Janeiro",
};
